server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  ai:
    dashscope:
     api-key: ${DASH_SCOPE_API_KEY}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG